### ISSUE TITLE
Not compatible with 1.16.3

### ISSUE THREAD

**Issue by Entoarox** [MongoTheElder/HarvestSprites#3]
I am not certain if you are aware, but this mod is currently not compatible with 1.16.3, I would really love it if it could be, as I really enjoy it!

**Comment by MongoTheElder** [comment]
Yeah, I haven't had time to update this for 1.16.3 yet, it is next on the list

**Comment by Entoarox** [comment]
Awesome, cant wait to have it! 😄

**Comment by MongoTheElder** [comment]
1.16.3-1.1.0 has been released!

**Comment by Entoarox** [comment]
Thanks a bunch, really want you to know that! 😄
